BASE_MODEL = "distilbert-base-multilingual-cased"
DATASET_CSV = "data/sms_dataset.csv"
MODEL_OUTPUT_DIR = "../model"

NUM_TRAIN_EPOCHS = 5
PER_DEVICE_TRAIN_BATCH_SIZE = 32
PER_DEVICE_EVAL_BATCH_SIZE = 64
LEARNING_RATE = 2e-5
WEIGHT_DECAY = 0.01
WARMUP_RATIO = 0.1
MAX_LENGTH = 128
LOGGING_STEPS = 50
